# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: frontend
build:
  artifacts:
  - image: frontend
deploy:
  kubectl:
    manifests:
    - ./frontend.yaml

---

apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: frontend-accounts
requires:
  - configs: [frontend]
  - git:
      repo: https://github.com/gsquared94/bank-of-anthos-userservice
  - git:
      repo: https://github.com/gsquared94/bank-of-anthos-contacts

---

apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: frontend-transactions
requires:
  - configs: [frontend]
  - git:
      repo: https://github.com/gsquared94/bank-of-anthos-ledgerwriter
  - git:
      repo: https://github.com/gsquared94/bank-of-anthos-balancereader
  - git:
      repo: https://github.com/gsquared94/bank-of-anthos-transactionhistory
